export const CONTACT_FORM_LABELS = {
  enquiryTitle: 'Send a message',
  enquiryLead: 'Ask about a month-long stay, the boat, or anything else. To take the villa, switch to booking.',
  bookTitle: 'Book the apartment',
  bookLead: 'You are requesting the whole villa for your group. We will take you to finish the booking.',
  intentEnquiry: 'General enquiry',
  intentBook: 'Book the apartment',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  mobile: 'Mobile (WhatsApp)',
  checkIn: 'Check-in',
  checkOut: 'Check-out',
  adults: 'Adults',
  children: 'Children',
  roomType: 'Stay',
  roomTypeDefault: 'The whole apartment',
  message: 'Your message',
  messagePlaceholder: 'Tell us about your group, or any notes for your stay…',
  requests: 'Special requests',
  requestsPlaceholder: 'Anything we should know ahead of your stay?',
  submit: 'Send enquiry',
  submitting: 'Sending…',
  continueBook: 'Continue to booking',
  switchBook: 'I want to book the apartment',
  switchEnquiry: 'Just send a message',
}
